## Import the modules

In [1]:
import pandas as pd

## Import the data

In [3]:
data = pd.read_csv('../data/AllMoviesDetailsCleaned.csv', delimiter= ';')
data.head()

/tmp/ipykernel_3596/3682371494.py:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('../data/AllMoviesDetailsCleaned.csv', delimiter= ';')

,id,budget,genres,imdb_id,original_language,original_title,overview,popularity,production_companies,production_countries,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,production_companies_number,production_countries_number,spoken_languages_number
0,2,0,Drama|Crime,tt0094675,fi,Ariel,Taisto Kasurinen is a Finnish coal miner whose...,0.823904,Villealfa Filmproduction Oy,Finland,...,69.0,suomi,Released,NaN,Ariel,7.1,40,2,1,2
1,3,0,Drama|Comedy,tt0092149,fi,Varjoja paratiisissa,"An episode in the life of Nikander, a garbage ...",0.47445,Villealfa Filmproduction Oy,Finland,...,76.0,English,Released,NaN,Shadows in Paradise,7.0,32,1,1,3
2,5,4000000,Crime|Comedy,tt0113101,en,Four Rooms,It's Ted the Bellhop's first night on the job....,1.698,Miramax Films,United States of America,...,98.0,English,Released,Twelve outrageous guests. Four scandalous requ...,Four Rooms,6.5,485,2,1,1
3,6,0,Action|Thriller|Crime,tt0107286,en,Judgment Night,"While racing to a boxing match, Frank, Mike, J...",1.32287,Universal Pictures,Japan,...,110.0,English,Released,Don't move. Don't whisper. Don't even breathe.,Judgment Night,6.5,69,3,2,1
4,8,42000,Documentary,tt0825671,en,Life in Loops (A Megacities RMX),Timo Novotny labels his new project an experim...,0.054716,inLoops,Austria,...,80.0,English,Released,A Megacities remix.,Life in Loops (A Megacities RMX),6.4,4,1,1,5

In [8]:
df = data.copy()

## Understanding the Dataset

In [10]:
# all the columns present in the dataframe
df.columns

Index(['id', 'budget', 'genres', 'imdb_id', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'production_companies_number',
       'production_countries_number', 'spoken_languages_number'],
      dtype='object')

In [12]:
# info of all the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 329044 entries, 0 to 329043
Data columns (total 22 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   id                           329044 non-null  int64
 1   budget                       329044 non-null  int64
 2   genres                       207515 non-null  object
 3   imdb_id                      250564 non-null  object
 4   original_language            328841 non-null  object
 5   original_title               329043 non-null  object
 6   overview                     278060 non-null  object
 7   popularity                   329044 non-null  object
 8   production_companies         329044 non-null  object
 9   production_countries         329044 non-null  object
 10  release_date                 304998 non-null  object
 11  revenue                      329044 non-null  int64
 12  runtime                      292252 non-null  float64
 13  spoken_languages             324584 non-null  object
 14  status                       327056 non-null  object
 15  tagline                      52931 non-null   object
 16  title                        329043 non-null  object
 17  vote_average                 329044 non-null  float64
 18  vote_count                   329044 non-null  int64
 19  production_companies_number  329044 non-null  int64
 20  production_countries_number  329044 non-null  int64
 21  spoken_languages_number      329044 non-null  int64
dtypes: float64(2), int64(7), object(13)
memory usage: 55.2+ MB

In [16]:
# Percentage null in each columns
df.isna().sum() * 100/len(df)

id                              0.000000
budget                          0.000000
genres                         36.933966
imdb_id                        23.850914
original_language               0.061694
original_title                  0.000304
overview                       15.494584
popularity                      0.000000
production_companies            0.000000
production_countries            0.000000
release_date                    7.307837
revenue                         0.000000
runtime                        11.181483
spoken_languages                1.355442
status                          0.604175
tagline                        83.913702
title                           0.000304
vote_average                    0.000000
vote_count                      0.000000
production_companies_number     0.000000
production_countries_number     0.000000
spoken_languages_number         0.000000
dtype: float64

## Scrape additional information

In [33]:
import asyncio
import requests
import imdb

In [43]:
url = f'https://api.themoviedb.org/3/movie/1029827?api_key=279ec8b5e677bfd655c30c6403e14469'

response = requests.get(url)
json.dumps(response.json())

'{"adult": false, "backdrop_path": "/zfS6OVeKeuV2ocMSEJ2WuMQX1nR.jpg", "belongs_to_collection": {"id": 1029834, "name": "Drishyam Collection", "poster_path": null, "backdrop_path": "/b0omVIe88I2gPIPmX87VYScMsx5.jpg"}, "budget": 0, "genres": [{"id": 80, "name": "Crime"}, {"id": 53, "name": "Thriller"}, {"id": 18, "name": "Drama"}, {"id": 9648, "name": "Mystery"}], "homepage": "", "id": 1029827, "imdb_id": "tt15501640", "original_language": "hi", "original_title": "\\u0926\\u0943\\u0936\\u094d\\u092f\\u092e \\u0968", "overview": "7 years after the case related to Vijay Salgaonkar and his family was closed, a series of unexpected events bring truth to light that threatens to change everything for the Salgaonkars. Can Vijay save his family this time?", "popularity": 15.266, "poster_path": "/yJNNwHQuKYNeHFbsxSFR6yK9Dda.jpg", "production_companies": [{"id": 3522, "logo_path": "/d3u51JgEP5KwPfxS13ocqvtzZeX.png", "name": "T-Series", "origin_country": "IN"}, {"id": 6808, "logo_path": "/xa1Yz7B5eRC2F9oHA6mDn8NE6ci.png", "name": "Viacom18 Studios", "origin_country": "IN"}, {"id": 16401, "logo_path": "/khS7G0KzBoCYcLs4xuNjpuZjntR.png", "name": "Aashirvad Cinemas", "origin_country": "IN"}, {"id": 44223, "logo_path": "/dXTCqVltThpRPYeSeDUIFssM5Wu.png", "name": "Panorama Studios", "origin_country": "IN"}], "production_countries": [{"iso_3166_1": "IN", "name": "India"}], "release_date": "2022-11-18", "revenue": 0, "runtime": 142, "spoken_languages": [{"english_name": "Hindi", "iso_639_1": "hi", "name": "\\u0939\\u093f\\u0928\\u094d\\u0926\\u0940"}], "status": "Released", "tagline": "", "title": "Drishyam 2", "video": false, "vote_average": 8.286, "vote_count": 7}'

In [45]:
# creating instance of IMDb
ia = imdb.Cinemagoer()

# getting movie
movies = ia.get_movie('15501640')

print(movies.summary())

Movie
=====
Title: Drishyam 2 (2022)
Genres: Crime, Drama, Mystery, Thriller.
Director: Abhishek Pathak.
Writer: Jeethu Joseph, , Aamil Keeyan Khan, , Aamil Keeyan Khan, , Abhishek Pathak.
Cast: Ajay Devgn (Vijay Salgaonkar), Tabu (Meera Deshmukh), Akshaye Khanna (IG Tarun Ahlawat), Shriya Saran (Nandini Salgaonkar), Ishita Dutta (Anju Salgaonkar).
Runtime: 140.
Country: India.
Language: Hindi.
Rating: 8.8 (15532 votes).
Plot: A gripping tale of an investigation and a family which is threatened by it. Will Vijay Salgaonkar be able to protect his family this time?

In [93]:
# update the budget, revenue, popularity, average vote & vote count
count = 0

for row in df.itertuples():
    
    
    # get the details from tmdb
    url = f'https://api.themoviedb.org/3/movie/{row.id}?api_key=279ec8b5e677bfd655c30c6403e14469'
    
    response = requests.get(url)
    
    try:
        if( (df.loc[row.id]['revenue'] <= 0) and (int(json.dumps(response.json()['revenue'])) > 0)):
            df.loc[row.id, ('budget_new')] = int(json.dumps(response.json()['budget']))             
            df.loc[row.id, ('revenue_new')] = int(json.dumps(response.json()['revenue']))
            df.loc[row.id, ('popularity_new')] = json.dumps(response.json()['popularity'])
            df.loc[row.id, ('vote_average_new')] = float(json.dumps(response.json()['vote_average']))
            df.loc[row.id, ('vote_count_new')] = int(json.dumps(response.json()['vote_count']))
            df.loc[row.id, ('belongs_to_collection')] = json.dumps(response.json()['belongs_to_collection'])
            
            count += 1                     
    except:
        continue
       
print(count)

ConnectionError: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/16524?api_key=279ec8b5e677bfd655c30c6403e14469 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f337de38760>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

In [98]:
df_backup = df

In [102]:
# replace the original with the new data
df.loc[df['budget_new'] > 0, 'budget'] = df['budget_new']
df.loc[df['revenue_new'] > 0, 'revenue'] = df['revenue_new']
df.loc[df['popularity_new'] != None, 'popularity'] = df['popularity_new']
df.loc[df['vote_average_new'] > 0, 'vote_average'] = df['vote_average_new']
df.loc[df['vote_count_new'] > 0, 'vote_count'] = df['vote_count_new']
df.head()

,id,budget,genres,imdb_id,original_language,original_title,overview,popularity,production_companies,production_countries,...,vote_average,vote_count,production_companies_number,production_countries_number,spoken_languages_number,budget_new,revenue_new,popularity_new,vote_average_new,vote_count_new
0,2,0,Drama|Crime,tt0094675,fi,Ariel,Taisto Kasurinen is a Finnish coal miner whose...,NaN,Villealfa Filmproduction Oy,Finland,...,7.1,40,2,1,2,NaN,NaN,NaN,NaN,NaN
1,3,0,Drama|Comedy,tt0092149,fi,Varjoja paratiisissa,"An episode in the life of Nikander, a garbage ...",NaN,Villealfa Filmproduction Oy,Finland,...,7.0,32,1,1,3,NaN,NaN,NaN,NaN,NaN
2,5,4000000,Crime|Comedy,tt0113101,en,Four Rooms,It's Ted the Bellhop's first night on the job....,NaN,Miramax Films,United States of America,...,6.5,485,2,1,1,NaN,NaN,NaN,NaN,NaN
3,6,0,Action|Thriller|Crime,tt0107286,en,Judgment Night,"While racing to a boxing match, Frank, Mike, J...",NaN,Universal Pictures,Japan,...,6.5,69,3,2,1,NaN,NaN,NaN,NaN,NaN
4,8,42000,Documentary,tt0825671,en,Life in Loops (A Megacities RMX),Timo Novotny labels his new project an experim...,NaN,inLoops,Austria,...,6.4,4,1,1,5,NaN,NaN,NaN,NaN,NaN

In [103]:
df.to_csv('../data/modified.csv')