In [2]:
%load_ext autoreload
%autoreload 2

In [6]:
import pandas as pd
import numpy as np

from python_files.data import GetData

In [4]:
data = GetData().get_data()['AllDataMerged_updated']
data.head()

,id,budget,genres,imdb_id,original_language,production_companies,production_countries,release_date,revenue,runtime,...,actor5_name,actor5_gender,actor_number,director_name,director_gender,director_number,producer_name,producer_number,screeplay_name,editor_name
0,5,4000000,Crime|Comedy,tt0113101,en,Miramax Films,United States of America,25-12-1995,4300000,98.0,...,Marisa Tomei,1,24,Allison Anders,1.0,4,Lawrence Bender,1,none,Margaret Goodspeed
1,9,4000000,Drama,tt0425473,de,none,Germany,02-09-2004,4257354,15.0,...,none,0,2,Marc Meyer,0.0,2,Marc Meyer,1,none,Marc Meyer
2,11,11000000,Adventure|Action|Science Fiction,tt0076759,en,Lucasfilm,United States of America,25-05-1977,775398007,121.0,...,Alec Guinness,2,106,George Lucas,2.0,1,Gary Kurtz,2,none,Marcia Lucas
3,12,94000000,Animation|Family,tt0266543,en,Pixar Animation Studios,United States of America,30-05-2003,940335536,100.0,...,Brad Garrett,2,24,Andrew Stanton,2.0,1,Graham Walters,1,Andrew Stanton,David Ian Salter
4,13,55000000,Comedy|Drama|Romance,tt0109830,en,Paramount Pictures,United States of America,06-07-1994,677945399,142.0,...,Sally Field,1,67,Robert Zemeckis,2.0,1,Wendy Finerman,3,Eric Roth,Arthur Schmidt

In [8]:
df = data.copy()

In [10]:
df.shape

(8939, 37)

In [9]:
# Apply log feature to budget and revnue

df['budget_log'] = np.log(df['budget'])
df['revenue_log'] = np.log(df['revenue'])

In [11]:
# Define X and Y

X = df[['budget_log','runtime','production_companies_number','production_countries_number',
       'spoken_languages_number','director_number','producer_number','actor_number']]
y = df['revenue_log']